### ISSUE TITLE
Remix V2 Flat routes

### ISSUE THREAD

**Issue by mattcorner** [kiliman/remix-mount-routes#4]
I'm starting to play around with some the V2 Remix APIs, specifically the new route convention. Are there any plans to support this?

I haven't tested extensively, but immediately I started getting 404s for missing routes. Comparing the generated routes I can see for instance that:

### Index routes
Doesn't look like they are identified correctly anymore.
##### V1:
```
{
    "routes/sample/index": {
        "file": "routes/index.tsx",
        "id": "routes/sample/index",
        "index": true,
        "path": "sample"
    },
}
```
##### V2: 
```
{
   "routes/sample/_index": {
        "file": "routes/_index.tsx",
        "id": "routes/sample/_index",
        "path": "sample/_index"
    },
}
```

### Object keys
Not sure if this has any effect, but I note that they have changed in V2.
##### V1: 
```
{
"routes/sample/abc/def": { ... }
}
```
##### V2:
```
{
"routes/test/abc.def": { ... }
}
```

### ParentId not being populated:
Looks like parent routes are no longer identified.
##### V1:
```
{
    "routes/sample/abc/$id/def": {
        "file": "routes/abc/$id/def.ts",
        "id": "routes/sample/abc/$id/def",
        "parentId": "routes/sample/abc/$id",
        "path": "def"
    },
}
```
##### V2:
```
{
    "routes/sample/abc.$id.def": {
        "file": "routes/abc.$id.def.tsx",
        "id": "routes/sample/abc.$id.def",
        "path": "sample/abc/:id/def"
    }
}
```

**Comment by mattcorner** [comment]
Closing because I see that remix-flat-routes gives us the best of both worlds.

**Comment by kiliman** [comment]
Hi. Thanks! Yes, `remix-flat-routes` was the original implementation of Ryan's flat routes convention. Over the past year, I have extended it to provide more flexibility based on user feedback. 

Unfortunately, the `v2` routing convention that is _now_ in Remix core is based on the _original spec_ and doesn't include the extensions. I will maintain this library for those needing the additional functionality.

**Comment by mattcorner** [comment]
I've not seen anything concrete so wondering if you are more in the loop. Are remix planning to support `baseUrl` officially in v2, or is this likely to remain one of the enhancements that necessitate the use of `remix-flat-routes`? Appreciate that you may not know.

**Comment by kiliman** [comment]
Yeah, that's not something I'm in the loop about. Going forward, almost all router-related features will be introduced in React Router first. Interestingly RR already supports `basename`, but I'm unsure if it works with the new data router. It shouldn't be difficult to include.

https://reactrouter.com/en/main/router-components/router
